"""Load conversations from Claude Code transcript storage.

Claude Code writes one JSONL transcript per session under a per-workspace
project directory:

    ~/.claude/projects/<encoded_workspace>/<session_uuid>.jsonl
    ~/.claude/projects/<encoded_workspace>/<session_uuid>/subagents/<uuid>.jsonl

The directory name is a lossy encoding of the workspace path (every
non-alphanumeric character becomes ``-``), so it cannot be reliably decoded.
Every conversational record carries the real workspace in its ``cwd`` field,
which is what this loader uses. The directory name is only a fallback.

Each line is a JSON record with a ``type`` discriminator. The types that carry
conversation content are ``user`` and ``assistant``; their ``message`` field
follows the Anthropic Messages API shape (``role`` plus ``content`` as either a
string or a list of typed blocks). All other record types (``mode``,
``ai-title``, ``last-prompt``, ``attachment``, ``queue-operation``,
``permission-mode``, ``file-history-snapshot``, ``file-history-delta``,
``system``) are bookkeeping and are skipped.

Tool calls appear as ``tool_use`` blocks on assistant records and are answered
by ``tool_result`` blocks on the following user record; they are paired here and
condensed into a single tool-context message, mirroring how ide_loader handles
Kiro's tool_call/tool_result stream.
"""

import json
import logging
import re
from datetime import datetime
from pathlib import Path

from .config import ClaudeSourceConfig, get_config
from .ide_loader import _parse_timestamp, _replace_code_blocks
from .models import ContentTier, IndexedMessage, SessionInfo, Source
from .tool_summaries import ToolSummaryConfig, _looks_meaningful

logger = logging.getLogger(__name__)

# Records whose text is harness plumbing rather than conversation.
_SKIP_PREFIXES = (
    "<local-command-stdout>",
    "<local-command-caveat>",
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<user-prompt-submit-hook>",
    "Caveat: The messages below were generated by the user while running",
    "[Request interrupted",
    "API Error:",
)

# Injected context blocks that wrap real user text; stripped, not skipped.
_SYSTEM_REMINDER_RE = re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL)

# How many leading records to scan for a workspace/timestamp before giving up.
_HEADER_SCAN_LINES = 40

# Maps session_id -> transcript path, populated by list_claude_sessions().
_session_paths: dict[str, Path] = {}


def _get_claude_config() -> ClaudeSourceConfig:
    return get_config().claude


def get_claude_roots() -> list[Path]:
    """Return the configured Claude Code project roots that exist on disk."""
    return _get_claude_config().get_roots()


def _decode_project_dir_name(dirname: str) -> str:
    """Best-effort reversal of Claude Code's workspace directory encoding.

    The encoding replaces every non-alphanumeric character with ``-``, so a
    path component containing a hyphen is indistinguishable from a separator.
    We only recover the unambiguous part — a leading Windows drive letter —
    and otherwise hand back the raw name. This is a last resort; the ``cwd``
    field inside the transcript is authoritative.
    """
    match = re.match(r"^([A-Za-z])--(.*)$", dirname)
    if match:
        return f"{match.group(1).upper()}:\\{match.group(2)}"
    return dirname


def _strip_system_reminders(text: str) -> str:
    """Remove injected <system-reminder> blocks from user text."""
    return _SYSTEM_REMINDER_RE.sub("", text)


def _should_skip_text(text: str) -> bool:
    """Check whether a message body is harness plumbing rather than content."""
    return any(text.startswith(prefix) for prefix in _SKIP_PREFIXES)


def _read_session_header(path: Path) -> tuple[str, datetime | None]:
    """Scan the head of a transcript for its workspace and first timestamp.

    Stops as soon as both are known. Returns ``("", None)`` if neither is
    found within the first few records.
    """
    workspace = ""
    first_ts: datetime | None = None
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            for line_no, line in enumerate(f):
                if line_no >= _HEADER_SCAN_LINES:
                    break
                line = line.strip()
                if not line:
                    continue
                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(record, dict):
                    continue
                if not workspace and record.get("cwd"):
                    workspace = str(record["cwd"])
                if first_ts is None and record.get("timestamp"):
                    first_ts = _parse_timestamp(record["timestamp"])
                if workspace and first_ts is not None:
                    break
    except OSError as e:
        logger.debug(f"Could not read Claude transcript header {path}: {e}")
    return workspace, first_ts


def _build_session_info(
    path: Path, session_id: str, fallback_workspace: str
) -> SessionInfo | None:
    """Build a SessionInfo for one transcript file, or None if unusable."""
    try:
        stat = path.stat()
    except OSError as e:
        logger.debug(f"Could not stat Claude transcript {path}: {e}")
        return None

    if stat.st_size == 0:
        return None

    workspace, created = _read_session_header(path)

    return SessionInfo(
        session_id=session_id,
        workspace=workspace or fallback_workspace,
        created=created or datetime.fromtimestamp(stat.st_ctime),
        modified=datetime.fromtimestamp(stat.st_mtime),
        source=Source.CLAUDE,
    )


def list_claude_sessions() -> list[SessionInfo]:
    """List all Claude Code sessions across the configured project roots.

    Main transcripts live directly under the project directory. Subagent
    transcripts live under ``<session_id>/subagents/`` and are listed as
    sessions in their own right (id ``<parent>-sub-<uuid>``) when
    ``include_subagents`` is enabled, since they hold conversation the main
    transcript only references by tool call.
    """
    config = _get_claude_config()
    sessions: list[SessionInfo] = []
    paths: dict[str, Path] = {}

    for root in config.get_roots():
        try:
            project_dirs = [d for d in root.iterdir() if d.is_dir()]
        except OSError as e:
            logger.warning(f"Could not list Claude project root {root}: {e}")
            continue

        for project_dir in project_dirs:
            fallback_workspace = _decode_project_dir_name(project_dir.name)

            try:
                transcripts = sorted(project_dir.glob("*.jsonl"))
            except OSError as e:
                logger.debug(f"Could not list transcripts in {project_dir}: {e}")
                continue

            for transcript in transcripts:
                session = _build_session_info(
                    transcript, transcript.stem, fallback_workspace
                )
                if session and session.session_id not in paths:
                    paths[session.session_id] = transcript
                    sessions.append(session)

            if not config.include_subagents:
                continue

            try:
                subagent_files = sorted(project_dir.glob("*/subagents/*.jsonl"))
            except OSError as e:
                logger.debug(f"Could not list subagents in {project_dir}: {e}")
                continue

            for transcript in subagent_files:
                parent_id = transcript.parent.parent.name
                session_id = f"{parent_id}-sub-{transcript.stem}"
                session = _build_session_info(
                    transcript, session_id, fallback_workspace
                )
                if session and session.session_id not in paths:
                    paths[session.session_id] = transcript
                    sessions.append(session)

    _session_paths.update(paths)
    return sessions


def _find_session_file(session_id: str) -> Path | None:
    """Resolve a session_id to its transcript path, rescanning if needed."""
    path = _session_paths.get(session_id)
    if path is not None and path.exists():
        return path

    # Index is stale or this process never listed sessions — rebuild it.
    list_claude_sessions()
    path = _session_paths.get(session_id)
    if path is not None and path.exists():
        return path
    return None


def _describe_claude_tool_call(tool_name: str, tool_input: dict) -> str:
    """Generate a compact one-line description of a Claude Code tool call."""
    if not isinstance(tool_input, dict):
        return ""

    try:
        if tool_name in ("Read", "Write", "NotebookEdit"):
            return str(tool_input.get("file_path", "") or "(unknown path)")

        if tool_name == "Edit":
            path = str(tool_input.get("file_path", "") or "(unknown path)")
            return f"{path} (replace_all)" if tool_input.get("replace_all") else path

        if tool_name in ("Bash", "PowerShell"):
            command = str(tool_input.get("command", ""))
            if len(command) > 100:
                command = command[:97] + "..."
            return command or "(no command)"

        if tool_name == "Glob":
            pattern = tool_input.get("pattern", "")
            path = tool_input.get("path", "")
            return f'pattern="{pattern}" in {path}' if path else f'pattern="{pattern}"'

        if tool_name == "Grep":
            pattern = tool_input.get("pattern", "")
            path = tool_input.get("path", "")
            return f'pattern="{pattern}" in {path}' if path else f'pattern="{pattern}"'

        if tool_name in ("Task", "Agent"):
            subagent = tool_input.get("subagent_type", tool_input.get("description", ""))
            prompt = str(tool_input.get("prompt", ""))
            if len(prompt) > 100:
                prompt = prompt[:97] + "..."
            return f'{subagent}: "{prompt}"'

        if tool_name == "WebFetch":
            return str(tool_input.get("url", "") or "(no url)")

        if tool_name == "WebSearch":
            return f'query="{tool_input.get("query", "")}"'

        if tool_name == "Skill":
            skill = tool_input.get("skill", "")
            args = str(tool_input.get("args", ""))
            return f"{skill} {args}".strip() or "(no skill)"

        if tool_name == "TodoWrite":
            todos = tool_input.get("todos", [])
            if isinstance(todos, list):
                return f"{len(todos)} todos"
            return "(todos)"

        serialized = json.dumps(tool_input, ensure_ascii=False)
        if len(serialized) > 100:
            serialized = serialized[:97] + "..."
        return serialized

    except (TypeError, ValueError):
        return ""


def _tool_result_text(block: dict, tool_use_result: object) -> str:
    """Flatten a tool_result block (and its structured sibling) into text.

    The ``content`` of a tool_result block is a string or a list of typed
    blocks. Claude Code additionally stores a richer, structured version of
    the same result on the record as ``toolUseResult``; we prefer the block
    content and fall back to the structured form.
    """
    content = block.get("content")
    parts: list[str] = []

    if isinstance(content, str):
        parts.append(content)
    elif isinstance(content, list):
        for item in content:
            if isinstance(item, dict):
                if item.get("type") == "text" or "text" in item:
                    parts.append(str(item.get("text", "")))
            elif isinstance(item, str):
                parts.append(item)

    text = "\n".join(p for p in parts if p)
    if text.strip():
        return text

    if isinstance(tool_use_result, str):
        return tool_use_result
    if isinstance(tool_use_result, dict):
        for key in ("stdout", "stderr", "content", "output", "result", "error"):
            value = tool_use_result.get(key)
            if isinstance(value, str) and value.strip():
                return value
        try:
            return json.dumps(tool_use_result, ensure_ascii=False)
        except (TypeError, ValueError):
            return ""
    return ""


def _generate_claude_tool_summary(
    tool_use: dict,
    tool_result: dict,
    tool_use_result: object,
    config: ToolSummaryConfig,
) -> str | None:
    """Summarize a Claude Code tool_use/tool_result pair.

    Returns None when the tool is excluded by configuration.
    """
    tool_name = str(tool_use.get("name", "") or "unknown")
    if tool_name in config.excluded_tools:
        return None

    description = _describe_claude_tool_call(tool_name, tool_use.get("input", {}))
    description = description.replace("\n", " ").replace("\r", " ").strip()
    if not description:
        description = "(no input)"

    outcome = "failed" if tool_result.get("is_error") else "completed"
    summary = f"[{tool_name}] {description} → {outcome}"

    if config.include_meaningful_output:
        text = _tool_result_text(tool_result, tool_use_result)
        # Errors are always worth keeping; otherwise apply the same
        # signal heuristic used for Kiro tool output.
        if text and (tool_result.get("is_error") or _looks_meaningful(text)):
            meaningful = text[:497] + "..." if len(text) > 500 else text
            summary = f"{summary}\n{meaningful}"
        else:
            summary = f"{summary}\n(no meaningful output)"

    if len(summary) > config.max_summary_length:
        summary = summary[: config.max_summary_length - 3] + "..."

    return summary


def _make_message(
    session: SessionInfo,
    uuid: str,
    timestamp: datetime,
    role: str,
    text: str,
    index: int,
    tier: ContentTier = ContentTier.CONVERSATION,
    tool_name: str | None = None,
) -> IndexedMessage:
    return IndexedMessage(
        uuid=uuid,
        session_id=session.session_id,
        workspace=session.workspace,
        timestamp=timestamp,
        role=role,
        searchable_text=text,
        message_index=index,
        source=Source.CLAUDE,
        content_tier=tier,
        tool_name=tool_name,
    )


def load_claude_session_messages(session: SessionInfo) -> list[IndexedMessage]:
    """Load indexable messages from one Claude Code transcript.

    Extracts user text, assistant text, optionally assistant thinking, and
    tool-context summaries built from paired tool_use/tool_result blocks.
    """
    transcript = _find_session_file(session.session_id)
    if not transcript:
        return []

    claude_config = _get_claude_config()
    summaries = get_config().tool_summaries
    tool_config = ToolSummaryConfig(
        excluded_tools=summaries.excluded_tools,
        max_summary_length=summaries.max_summary_length,
        include_meaningful_output=summaries.include_meaningful_output,
    )

    messages: list[IndexedMessage] = []
    pending_tool_uses: dict[str, dict] = {}
    msg_idx = 0

    try:
        with open(transcript, encoding="utf-8", errors="replace") as f:
            for line_no, line in enumerate(f):
                line = line.strip()
                if not line:
                    continue

                try:
                    record = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(record, dict):
                    continue

                record_type = record.get("type")
                if record_type not in ("user", "assistant"):
                    continue

                # isMeta marks harness-injected pseudo-turns (command caveats,
                # local command output) that are not part of the conversation.
                if record.get("isMeta"):
                    continue

                if record.get("isSidechain") and not claude_config.include_sidechains:
                    continue

                message = record.get("message")
                if not isinstance(message, dict):
                    continue

                timestamp = (
                    _parse_timestamp(record.get("timestamp"))
                    or session.modified
                    or datetime.now()
                )
                record_uuid = str(
                    record.get("uuid") or f"{session.session_id}-{line_no}"
                )
                content = message.get("content")

                # A bare string is always plain conversation text.
                if isinstance(content, str):
                    text = _strip_system_reminders(content).strip()
                    if not text or _should_skip_text(text):
                        continue
                    messages.append(
                        _make_message(
                            session,
                            record_uuid,
                            timestamp,
                            record_type,
                            _replace_code_blocks(text),
                            msg_idx,
                        )
                    )
                    msg_idx += 1
                    continue

                if not isinstance(content, list):
                    continue

                for block_no, block in enumerate(content):
                    if not isinstance(block, dict):
                        continue
                    block_type = block.get("type")

                    if block_type == "text":
                        text = _strip_system_reminders(str(block.get("text", ""))).strip()
                        if not text or _should_skip_text(text):
                            continue
                        messages.append(
                            _make_message(
                                session,
                                f"{record_uuid}-{block_no}",
                                timestamp,
                                record_type,
                                _replace_code_blocks(text),
                                msg_idx,
                            )
                        )
                        msg_idx += 1

                    elif block_type == "thinking":
                        if not claude_config.include_thinking:
                            continue
                        text = str(block.get("thinking", "")).strip()
                        if not text:
                            continue
                        messages.append(
                            _make_message(
                                session,
                                f"{record_uuid}-{block_no}",
                                timestamp,
                                "assistant",
                                _replace_code_blocks(text),
                                msg_idx,
                            )
                        )
                        msg_idx += 1

                    elif block_type == "tool_use":
                        if not claude_config.include_tool_context:
                            continue
                        tool_use_id = block.get("id")
                        if tool_use_id:
                            pending_tool_uses[str(tool_use_id)] = block

                    elif block_type == "tool_result":
                        if not claude_config.include_tool_context:
                            continue
                        tool_use_id = str(block.get("tool_use_id", ""))
                        tool_use = pending_tool_uses.pop(tool_use_id, None)
                        if not tool_use:
                            continue
                        summary = _generate_claude_tool_summary(
                            tool_use, block, record.get("toolUseResult"), tool_config
                        )
                        if not summary:
                            continue
                        messages.append(
                            _make_message(
                                session,
                                f"{record_uuid}-{block_no}-tool-ctx",
                                timestamp,
                                "assistant",
                                summary,
                                msg_idx,
                                tier=ContentTier.TOOL_CONTEXT,
                                tool_name=str(tool_use.get("name", "")) or None,
                            )
                        )
                        msg_idx += 1

    except OSError as e:
        logger.warning(f"Error loading Claude session {session.session_id}: {e}")

    return messages
